FROM python:3.8-slim-buster
WORKDIR /orderapp

COPY requirements.txt /orderapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /orderapp

EXPOSE 5002

# Start the Flask app
#ENTRYPOINT [ "python" ]
#CMD [ "app.py" ]
CMD ["ddtrace-run" "python" "app.py" "-Ddd.service=order" "-Ddd.env=micro-service" "-Ddd.version=1.1"]