FROM python:3.8-slim-buster

ENV DD_SERVICE="book-svc"
ENV DD_ENV="micro"
ENV DD_VERSION="0.1.0"

LABEL com.datadoghq.tags.service="book-svc"
LABEL com.datadoghq.tags.env="micro"
LABEL com.datadoghq.tags.version="0.1.0"

WORKDIR /bookapp

COPY requirements.txt /bookapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /bookapp

EXPOSE 5004

# Start the Flask app
ENTRYPOINT ["ddtrace-run"]
#CMD ["python3" "app.py"]
CMD python3 app.py
