FROM python:3.8-slim-buster

ENV DD_SERVICE="user-svc"
ENV DD_ENV="micro"
ENV DD_VERSION="0.1.0"

LABEL com.datadoghq.tags.service="user-svc"
LABEL com.datadoghq.tags.env="micro"
LABEL com.datadoghq.tags.version="0.1.0"

WORKDIR /userapp

COPY requirements.txt /userapp/requirements.txt
RUN pip3 install -r requirements.txt

COPY . /userapp

EXPOSE 5003

# Start the Flask app
ENTRYPOINT ["ddtrace-run"]
CMD python3 app.py
