version: "3.8"

volumes:
  userapp:
  bookapp:
  orderapp:
  frontendapp:
  
services:
  user-svc: 
    container_name: user-svc-c
    build: ./user
    ports:
      - "5003:5003"
    volumes:
      - userapp:/userapp
    restart: unless-stopped
    environment:
      - DD_AGENT_HOST=host.docker.internal    
    
  book-svc:
    container_name: book-svc-c
    build: ./book
    ports:
      - "5004:5004"
    volumes:
      - bookapp:/bookapp
    restart: unless-stopped
    environment:
      - DD_AGENT_HOST=host.docker.internal
      
  order-svc:
    container_name: order-svc-c
    build: ./order
    ports:
      - "5002:5002"
    volumes:
      - orderapp:/orderapp
    restart: unless-stopped
    environment:
      - DD_AGENT_HOST=host.docker.internal
      
  frontend-svc:
    container_name: frontend-svc-c
    build: ./frontend
    ports:
      - "5005:5005"
    volumes:
      - frontendapp:/frontendapp
    restart: unless-stopped
    extra_hosts:                             
      - "host.docker.internal:host-gateway"
    environment:
      - DD_AGENT_HOST=host.docker.internal
